[package]
name = "tantivy"
version = "0.1.1"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]
build = "build.rs"
license = "MIT"

description = """Tantivy is a search engine library."""

documentation = "http://fulmicoton.com/tantivy/tantivy/index.html"
homepage = "https://github.com/fulmicoton/tantivy"
repository = "https://github.com/fulmicoton/tantivy"

readme = "README.md"
keywords = ["search", "information", "retrieval"]

[dependencies]
byteorder = "0.4"
memmap = "0.2"
lazy_static = "0.1"
regex = "0.1"
fst = ">= 0.1.34"
atomicwrites = "0.0.14"
tempfile = "2.0"
rustc-serialize = "0.3.16"
file-lock = "0.0.17"
log = "0.3"
combine = "1.3"
tempdir = "0.3"
bincode = "0.4"
libc = "0.2.6"
num_cpus = "0.2"
itertools = "0.4"
lz4 = "1.13"
time = "0.1"
uuid = "0.1"
chan = "0.1"
crossbeam = "0.2"

[dev-dependencies]
rand = "0.3.13"

[build-dependencies]
gcc = "0.3.24"

# [profile.release]
# debug = true


